plugins:
#  golint:
#    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true
#  golangci-lint:
#    enabled: true
exclude_patterns:
  - "."
  - "**/*.pb.go"
  - "**/rln/contracts/*.go"
  - "**/bindata.go"
  - "./examples/waku-csharp"
  - "./examples/swift-waku"
